sudo: required
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.21.2
git:
  depth: false
jobs:
  include:
    stage: linting
    script:
      sudo make lint
    stage: tests
    before_script:
      sudo make db/upgrade
    script:
      sudo make tests