sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION=1.21.2
  PYTHONPATH=src:test
  APPLICATION_POSTGRES_USER=ubuntu
  APPLICATION_POSTGRES_HOST=127.0.0.1
  APPLICATION_POSTGRES_PORT=5432
  APPLICATION_POSTGRES_DB=travis_test
git:
  depth: false
jobs:
  include:
    stage: linting
    script:
      sudo make lint
    stage: tests
    script:
      sudo make tests