sudo: required
language: python
python:
  - "3.4"
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION=1.21.2
  APPLICATION_POSTGRES_USER=ubuntu
  APPLICATION_POSTGRES_HOST=127.0.0.1
  APPLICATION_POSTGRES_PORT=5432
  APPLICATION_POSTGRES_DB=travis_test
  ENVIRONEMENT=DEV
  IMPORT_PATH=/mnt/test/fixture
  PYTHONPATH=$PYTHONPATH:src:test
  PYTHONUSERBASE=/mnt/vendor
  DB_CONTAINER=DB
  APPLICATION_HOST=0.0.0.0
  APPLICATION_PORT=3000
git:
  depth: false
before_install:
  sudo mkdir -p /mnt/vendor
jobs:
  include:
    stage: linting
    before_script:
      pip install flake8
    script:
      python -m flake8 ./src ./test
    stage: tests
    before_script:
      touch .env
    script:
      sudo make tests
stages:
  - linting
  - tests
deploy:
  provider: heroku
  api_key:
    secure: "U1+ZmPqsdMHHKv+a6iMR5HMa76G0OQv1u9dvXzelOv45WZ89+ZGibGaC/6+6r7SDoE0DkqmU7FjCVhSmXNVFwTnzelGt+gQb+Rr9t3b8jLt1B76yISvhk6OaDyUCGvWmN/rVVRT3Mc/+dtsGeK9vXbtTxU6F5ryFFajs6Ztga9FBxlr/9WzghhFnDBBjdmDgF9Y9DVQhighQ0eQfuVa8LO6Kc6fN1lNUyAvWq85sVE1a5TresppQ7HpB+GT08pOcszsay7oEKf3z29asKfIb1MBnDD82WgMaVH+EdE1FNjlQ+rcpFG16p6xncaTWjjjBpAJ9jZDDoxPCCKnQufbkA8VTRM2gSBvVkZ1JIrvj2pCtDgMz6256T6cBSu2pEK9oDOJ0v+3L7gFHxbUJK3AtTNAd9uKIDO3IhU3TVee09ykcH2F8r5pU8dbV9NbZJwdXQtHz0gjsTm7K3yPmffr7IJ8a9pc6pU3Y127NQlYUwIIJhtuF2QB8Hj9o091nYlqRiMgJk8QYt+BRUjU8/BNc9RIK9jZJzixbirMxCCIdJFYeK7xuWz8ELBq7ZMXr1sgjP+iWweHv6mwF1+KZfySIBPFg9veJrcKUhqTTJo8lQaCA3zBJdnAHgUMTJT9+mGnuiROfbo/ngUymXMn/KvWJllwdHt2IJ/m+U2wuZnms0GA="
  app: data-esr-bce
  run:
    - "python src/server.py"
