FROM python:3.4

WORKDIR /mnt

ENV PYTHONUNBUFFERED 1
ENV ENVIRONEMENT DEV
ENV IMPORT_PATH /mnt/test/fixture
ENV PYTHONPATH $PYTHONPATH:src:test
ENV PYTHONUSERBASE /mnt/vendor
ENV DB_CONTAINER DB
ENV APPLICATION_HOST 0.0.0.0
ENV APPLICATION_PORT 3000

EXPOSE 3000

CMD ['python'; 'src/server.py']