version: 2
jobs:
   build:
     environment:
       PYTHONPATH: src:test
       APPLICATION_POSTGRES_USER: ubuntu
       APPLICATION_POSTGRES_HOST: 127.0.0.1
       APPLICATION_POSTGRES_PORT: 5432
       APPLICATION_POSTGRES_DB: circle_test
     docker:
       - image: circleci/python:3.4.8
     steps:
       - checkout
       - run:
          name: install dependencies
          command: pip install -r requirements-dev.txt
       - run:
          name: database
          command: python src/manage.py db upgrade
       - run:
          name: lint
          command: flake8 ./src ./test

       - run:
          name: test
          command:

           python -m pytest --junitxml=$CIRCLE_TEST_REPORTS/junit/report.xml test/
